.TH sacf 1 sacf\-VERSION
.SH NAME
sacf \- simple auto cpu frequencer
.SH SYNOPSIS
.B sacf
.RB [ \-blrtTv ]
.RB [ \-g
.IR governor ]
.P
.SH DESCRIPTION
.B sacf
is a simple auto cpu frequencer that only changes two things: the governor and
turbo boost state; depending on the cpu load, system load and the temperature.
Machines that have a battery and most of the time depend on it are the target,
but since it reduces the power consumption in general it can be beneficial
anyway, in theory. It needs root access to write to the system filesystem.
.P
.SH OPTIONS
.BR \-b ", " \-\-daemon
daemonize process, forks into the background.
.TP
.BI \-g " governor"
sets the governor of all cpus to governor, then exits.
.TP
.B \-l
prints the system info that sacf uses, then exits.
.TP
.B \-r
runs once, then exits (doesn't run forever).
.TP
.B \-t
enables turbo boost, then exits.
.TP
.B \-T
disbles turbo boost, then exits.
.TP
.B \-v
prints version information to stdout, then exits.
.SH SEE ALSO
.IR auto-cpufreq (1),
